### ISSUE TITLE
Is this completed?

### ISSUE THREAD

**Issue by lichinlichin** [lixingdecai/vue-toutiaohao#1]

**Comment by lixingdecai** [comment]
不好意思现在才看到，这个才刚上传，代码还在整理中，你是node什么版本，有执行npm install命令吗

**Comment by lichinlichin** [comment]
嗯嗯嗯 之前是friendly-errors-webpack-plugin没有在package.json的依赖里
然后添加完之后编译有很多eslint未通过 然后改完之后可以了

**Comment by lixingdecai** [comment]
恩 ，代码还在整理中。你是搜ueditor过来的么

**Comment by lichinlichin** [comment]
嗯咯 我是搜ueditor。
我最近也需要做一个编辑器，之前一直用的umeditor。
但是umeditor有很多问题，所以想改用ueditor，正好最近在边学边用vue，就想试试。
