### ISSUE TITLE
本地跑的时候报 vue-template-compiler版本冲突

### ISSUE THREAD

**Issue by tezml** [lixingdecai/vue-toutiaohao#5]

**Comment by tezml** [comment]
Vue packages version mismatch:

- vue@2.1.8
- vue-template-compiler@2.3.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by lixingdecai** [comment]
@tezml 你好, 这两个包的版本不对，可能你是安装了最新版本。可以试试指定版本安装

**Comment by tezml** [comment]
安装的就是package里的版本，而且按底下说法操作也没用

**Comment by lixingdecai** [comment]
package.json里面是允许小版本升级的。你把上面vue-template-compiler按里面的版本重新安装一次

**Comment by wk1025** [comment]
我的也是这个错误

不过重新安装就可以，并正常运行

npm remove vue
npm remove vue-template-compiler
npm remove vue-loader
npm install vue@2.1.8
npm install vue-template-compiler@2.1.8
npm install vue-loader@10.0.2

**Comment by lixingdecai** [comment]
@tezml @wk1025 确实存在该问题。一些版本依赖，小版本安装升级造成的问题。我试了下运行命令 npm i vue-template-compiler@2.1.8，重新安装vue-template-compiler到制定版本就可以了正常运行。
