### ISSUE TITLE
能不能把富文本那一块直接抽出来做成npm包，直接使用

### ISSUE THREAD

**Issue by engimatic** [lixingdecai/vue-toutiaohao#6]
能不能把富文本那一块直接抽出来做成npm包，图片视频上传使用自定义的服务器，在vue项目中直接引入使用

**Comment by lixingdecai** [comment]
@engimatic 你好。其实一开始是有这个打算。可是百度UEditor的核心文件ueditor.all.js、ueditor.config.js、ueditor.parser.js这几个文件都有进行侵入式的自定义修改。包一层NPM还是要抽象出这三个文件来修改，就没必要多此一举。我当初看的时候，百度UEditor就没有支持NPM，只有下载引入这种，不知道现在有没有支持。

**Comment by superhzx** [comment]
发表文章  发表视频 发表图集  这三个模块都是百度的 百度UEditor 实现的吗 ？

**Comment by lixingdecai** [comment]
百度的UEditor封装的太死了。 只有发表文章用的是百度的UEditor，而且是功能，我把UI自己重写了。还有第三方组件都没有使用UEditor,如果要使用的话得使用UEditor中的iframe的弹出框

**Comment by engimatic** [comment]
暂时没有实现
